In [15]:
import matplotlib.pyplot as plt
import numpy as np
import logging 

from neurolib.models.wc import WCModel
from neurolib.utils.parameterSpace import ParameterSpace
from neurolib.optimize.evolution import Evolution
import neurolib.utils.functions as func

from neurolib.utils.loadData import Dataset
ds = Dataset("hcp")

# a nice color map
plt.rcParams['image.cmap'] = 'plasma'

MainProcess root INFO     Loading dataset hcp from /opt/conda/lib/python3.9/site-packages/neurolib/utils/../data/datasets/hcp.
MainProcess root INFO     Dataset hcp loaded.


In [35]:
model2 = WCModel(Cmat = ds.Cmat, Dmat = ds.Dmat)
model2.params['exc_ext'] = 0.65

model2.params['signalV'] = 0
model2.params['duration'] = 20 * 1000 
model2.params['sigma_ou'] = 0.14
model2.params['K_gl'] = 3.15
model2.run()

MainProcess root INFO     wc: Model initialized.


In [51]:
ds.Cmat

array([[0.        , 0.07906338, 0.20767269, ..., 0.00061314, 0.0362114 ,
        0.00127439],
       [0.07906338, 0.        , 0.02107246, ..., 0.00191405, 0.00083845,
        0.0205666 ],
       [0.20767269, 0.02107246, 0.        , ..., 0.00106483, 0.01315564,
        0.00241511],
       ...,
       [0.00061314, 0.00191405, 0.00106483, ..., 0.        , 0.00192148,
        0.16260376],
       [0.0362114 , 0.00083845, 0.01315564, ..., 0.00192148, 0.        ,
        0.00413606],
       [0.00127439, 0.0205666 , 0.00241511, ..., 0.16260376, 0.00413606,
        0.        ]])

In [46]:
ds.Cmat

array([[0.        , 0.07906338, 0.20767269, ..., 0.00061314, 0.0362114 ,
        0.00127439],
       [0.07906338, 0.        , 0.02107246, ..., 0.00191405, 0.00083845,
        0.0205666 ],
       [0.20767269, 0.02107246, 0.        , ..., 0.00106483, 0.01315564,
        0.00241511],
       ...,
       [0.00061314, 0.00191405, 0.00106483, ..., 0.        , 0.00192148,
        0.16260376],
       [0.0362114 , 0.00083845, 0.01315564, ..., 0.00192148, 0.        ,
        0.00413606],
       [0.00127439, 0.0205666 , 0.00241511, ..., 0.16260376, 0.00413606,
        0.        ]])

In [36]:
model1 = WCModel(Cmat = ds.Cmat, Dmat = ds.Dmat)
model1.params['exc_ext'] = 0.65

model1.params['signalV'] = 0
model1.params['duration'] = 20 * 1000 
model1.params['sigma_ou'] = 0.14
model1.params['K_gl'] = 3.15
model1.run()

MainProcess root INFO     wc: Model initialized.


In [38]:
np.linalg.norm(model1.output - model2.output)/np.linalg.norm(model1.output)

1.0631516782635237

In [39]:
model1.output

array([[ 0.04811392,  0.05043035,  0.04776806, ...,  0.5194402 ,
         0.51584868,  0.51329819],
       [ 0.02191336,  0.02205247,  0.02345833, ...,  0.14544071,
         0.13748512,  0.13036306],
       [ 0.02176003,  0.02138803,  0.01980068, ...,  0.42253941,
         0.44582325,  0.4671384 ],
       ...,
       [ 0.03635697,  0.03672894,  0.04121749, ..., -0.25157832,
        -0.24534249, -0.24010168],
       [ 0.05141496,  0.05470537,  0.05680046, ...,  0.59035305,
         0.59070791,  0.59341936],
       [ 0.03072834,  0.03139116,  0.03353625, ...,  0.07349549,
         0.09661181,  0.11964385]])

In [40]:
model1.output - model2.output

array([[ 3.58865746e-02,  3.85093179e-02,  3.39798710e-02, ...,
         7.10545389e-02,  6.13198296e-02,  5.47937537e-02],
       [ 3.31670187e-03,  2.46411527e-03, -3.93106695e-04, ...,
        -6.58724412e-03, -1.56411815e-02, -2.40592215e-02],
       [-2.77255566e-02, -3.01858061e-02, -3.37135942e-02, ...,
         4.79490477e-01,  4.88816420e-01,  4.96526700e-01],
       ...,
       [ 3.26689653e-02,  3.01506877e-02,  3.32837997e-02, ...,
         1.61150034e-02,  2.49750992e-02,  3.05514138e-02],
       [ 4.29171531e-02,  4.42897048e-02,  4.21272523e-02, ...,
         1.11379080e-01,  9.86027499e-02,  9.42030559e-02],
       [-9.75758105e-03, -9.48197510e-03, -9.39125687e-03, ...,
         5.53440646e-02,  8.80984448e-02,  1.23306111e-01]])